import "./globals.css";
import ClientWrapper from "@/app/ClientWrapper";
import { AppProvider } from "@/context/CartContext";
import ThemeWrapper from "./ThemeWrapper";

export const metadata = {
  title: "Golden Coffee | قهوه طلایی",
  description: "Generated by create next app",
  icons: {
    icon: "/images/fav-icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="font-Dana">
        <AppProvider>
          <ThemeWrapper>
            <ClientWrapper>{children}</ClientWrapper>
          </ThemeWrapper>
        </AppProvider>
      </body>
    </html>
  );
}
